=== SteveIves/Demos/VB6/xml/rolodex.dtd
<?xml version="1.0"?>

  <!ELEMENT ROLODEX_LIST (ROLODEX*)>

    <!ELEMENT ROLODEX (CODE,TYPE,COMPANY?,STREET?,CITY?,STATE?,ZIP?,CONTACT?,PHONE?,FAX?,EMAIL?,WEBSITE?,MAILSHOT?,MEMO?,SPARE?)>

      <!ELEMENT CODE (#PCDATA)>
      <!ELEMENT TYPE (#PCDATA)>
      <!ELEMENT COMPANY (#PCDATA)>
      <!ELEMENT STREET (#PCDATA)>
      <!ELEMENT CITY (#PCDATA)>
      <!ELEMENT STATE (#PCDATA)>
      <!ELEMENT ZIP (#PCDATA)>
      <!ELEMENT CONTACT (#PCDATA)>
      <!ELEMENT PHONE (#PCDATA)>
      <!ELEMENT FAX (#PCDATA)>
      <!ELEMENT EMAIL (#PCDATA)>
      <!ELEMENT WEBSITE (#PCDATA)>
      <!ELEMENT MAILSHOT (#PCDATA)>
      <!ELEMENT MEMO (#PCDATA)>
      <!ELEMENT SPARE (#PCDATA)>

=== SteveIves/Demos/VB6/xml/rolodex.xml
<?xml version="1.0"?>

<!DOCTYPE ROLODEX_LIST SYSTEM "rolodex.dtd">

<ROLODEX_LIST>

  <ROLODEX>
    <CODE>0001</CODE>
    <TYPE>P</TYPE>
    <COMPANY>Hitchless Software</COMPANY>
    <STREET>Mooney Court</STREET>
    <CITY>Rancho Cordova</CITY>
    <STATE>CA</STATE>
    <ZIP>95670</ZIP>
    <CONTACT>William J Mooney</CONTACT>
    <PHONE>916 853 03</PHONE>
    <FAX>916 634 65</FAX>
    <EMAIL>William.Mooney@synergex.com</EMAIL>
    <WEBSITE>www.hitchless_software.com</WEBSITE>
    <MAILSHOT>Y</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0002</CODE>
    <TYPE>S</TYPE>
    <COMPANY>Brookline Wonderworks</COMPANY>
    <STREET>5786 Professional Drive</STREET>
    <CITY>Concrete</CITY>
    <STATE>AL</STATE>
    <ZIP>22142</ZIP>
    <CONTACT>Mark Coin</CONTACT>
    <PHONE>2152325656</PHONE>
    <FAX>2152325566</FAX>
    <EMAIL>mark@brookline.net</EMAIL>
    <WEBSITE>www.brookline.net</WEBSITE>
    <MAILSHOT>Y</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0005</CODE>
    <TYPE>C</TYPE>
    <COMPANY>Auto Experts</COMPANY>
    <STREET>921 Northgate Boulevard</STREET>
    <CITY>Stockton</CITY>
    <STATE>TX</STATE>
    <ZIP>77235</ZIP>
    <CONTACT>Gregory Edwards</CONTACT>
    <PHONE>8097819966</PHONE>
    <FAX>8097810099</FAX>
    <EMAIL>greg@autoexperts.com</EMAIL>
    <WEBSITE>www.autoexperts.com</WEBSITE>
    <MAILSHOT>Y</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0009</CODE>
    <TYPE>C</TYPE>
    <COMPANY>Cycle Gear Helmets</COMPANY>
    <STREET>3479 Orange Grove Lane</STREET>
    <CITY>Auburn</CITY>
    <STATE>CA</STATE>
    <ZIP>95687</ZIP>
    <CONTACT>Grey Hogue</CONTACT>
    <PHONE>9154886665</PHONE>
    <FAX>9154687799</FAX>
    <EMAIL>grey.hogue@cyclegear.com</EMAIL>
    <WEBSITE>www.cyclegear.com</WEBSITE>
    <MAILSHOT>Y</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0010</CODE>
    <TYPE>P</TYPE>
    <COMPANY>Gold Pointe Costumes</COMPANY>
    <STREET>3935 Fair Lane</STREET>
    <CITY>Watters</CITY>
    <STATE>KS</STATE>
    <ZIP>66528</ZIP>
    <CONTACT>Jonathan Carolina</CONTACT>
    <PHONE>8325698956</PHONE>
    <FAX></FAX>
    <EMAIL></EMAIL>
    <WEBSITE></WEBSITE>
    <MAILSHOT>N</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0111</CODE>
    <TYPE>O</TYPE>
    <COMPANY>Guns R Us</COMPANY>
    <STREET>210 A Rifle Court</STREET>
    <CITY>Sweda</CITY>
    <STATE>AL</STATE>
    <ZIP>55142</ZIP>
    <CONTACT>John Parker</CONTACT>
    <PHONE></PHONE>
    <FAX></FAX>
    <EMAIL></EMAIL>
    <WEBSITE></WEBSITE>
    <MAILSHOT>N</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0123</CODE>
    <TYPE>O</TYPE>
    <COMPANY>Carpet One</COMPANY>
    <STREET>452 Plush Drive</STREET>
    <CITY>Pile</CITY>
    <STATE>AL</STATE>
    <ZIP>52412</ZIP>
    <CONTACT>James Eaton</CONTACT>
    <PHONE></PHONE>
    <FAX></FAX>
    <EMAIL></EMAIL>
    <WEBSITE></WEBSITE>
    <MAILSHOT>N</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0125</CODE>
    <TYPE>P</TYPE>
    <COMPANY>McGuire Earth Works</COMPANY>
    <STREET>564 Eco Lane</STREET>
    <CITY>San Francisco</CITY>
    <STATE>CA</STATE>
    <ZIP>92045</ZIP>
    <CONTACT>Lance McGuire</CONTACT>
    <PHONE>4155665987</PHONE>
    <FAX>4155668988</FAX>
    <EMAIL>lance@earthworks.net</EMAIL>
    <WEBSITE>www.earthworks.net</WEBSITE>
    <MAILSHOT>Y</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0127</CODE>
    <TYPE>O</TYPE>
    <COMPANY>Jack Clancy and Associates</COMPANY>
    <STREET>404 Bridge Street</STREET>
    <CITY>Fair Oaks</CITY>
    <STATE>CA</STATE>
    <ZIP>95628</ZIP>
    <CONTACT>Jack Clancy</CONTACT>
    <PHONE>9168968686</PHONE>
    <FAX>9168967789</FAX>
    <EMAIL></EMAIL>
    <WEBSITE></WEBSITE>
    <MAILSHOT>N</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0134</CODE>
    <TYPE>S</TYPE>
    <COMPANY>Moth Hole</COMPANY>
    <STREET>491 Madison Avenue</STREET>
    <CITY>New York</CITY>
    <STATE>NY</STATE>
    <ZIP>02078</ZIP>
    <CONTACT>Paula Mace</CONTACT>
    <PHONE>9169011262</PHONE>
    <FAX>9166011131</FAX>
    <EMAIL></EMAIL>
    <WEBSITE></WEBSITE>
    <MAILSHOT>N</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0139</CODE>
    <TYPE>C</TYPE>
    <COMPANY>Waterproof Roofs</COMPANY>
    <STREET>800 Tar Way</STREET>
    <CITY>Academy</CITY>
    <STATE>WV</STATE>
    <ZIP>12569</ZIP>
    <CONTACT>Victor Palmer</CONTACT>
    <PHONE>2135589000</PHONE>
    <FAX>2135589800</FAX>
    <EMAIL>victor@waterproofroofs.com</EMAIL>
    <WEBSITE>www.waterproofroofs.com</WEBSITE>
    <MAILSHOT>Y</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0142</CODE>
    <TYPE>S</TYPE>
    <COMPANY>Green Thumb Grass</COMPANY>
    <STREET>852 Rosegarden Way</STREET>
    <CITY>Tracy</CITY>
    <STATE>AZ</STATE>
    <ZIP>85222</ZIP>
    <CONTACT>Heather Stahlberg</CONTACT>
    <PHONE>8552269569</PHONE>
    <FAX>8552254658</FAX>
    <EMAIL>heather@greenthumb.com</EMAIL>
    <WEBSITE>www.greenthumbgrass.com</WEBSITE>
    <MAILSHOT>Y</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0145</CODE>
    <TYPE>O</TYPE>
    <COMPANY>McGreevy Insurance</COMPANY>
    <STREET>83 Park Place</STREET>
    <CITY>Birmingham</CITY>
    <STATE>AL</STATE>
    <ZIP>24153</ZIP>
    <CONTACT>Glen McGreevy</CONTACT>
    <PHONE>5259698523</PHONE>
    <FAX>5257894562</FAX>
    <EMAIL></EMAIL>
    <WEBSITE></WEBSITE>
    <MAILSHOT>N</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0147</CODE>
    <TYPE>O</TYPE>
    <COMPANY>Sundance Carpet Repair</COMPANY>
    <STREET>1978 William Court</STREET>
    <CITY>Sherwin</CITY>
    <STATE>KY</STATE>
    <ZIP>44125</ZIP>
    <CONTACT>GL Moore</CONTACT>
    <PHONE>8954657878</PHONE>
    <FAX>8954658888</FAX>
    <EMAIL></EMAIL>
    <WEBSITE></WEBSITE>
    <MAILSHOT>N</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0150</CODE>
    <TYPE>O</TYPE>
    <COMPANY>Complete Auto Glass</COMPANY>
    <STREET>123 Mobile Court</STREET>
    <CITY>Rancho</CITY>
    <STATE>AL</STATE>
    <ZIP>33564</ZIP>
    <CONTACT>Mike Alvarez</CONTACT>
    <PHONE>4155551212</PHONE>
    <FAX>4155552222</FAX>
    <EMAIL></EMAIL>
    <WEBSITE></WEBSITE>
    <MAILSHOT>N</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0157</CODE>
    <TYPE>C</TYPE>
    <COMPANY>Paralegals USA</COMPANY>
    <STREET>3346 Airplay Way</STREET>
    <CITY>Bunny</CITY>
    <STATE>ME</STATE>
    <ZIP>02030</ZIP>
    <CONTACT>Gary Lane</CONTACT>
    <PHONE>8532563333</PHONE>
    <FAX>8532569999</FAX>
    <EMAIL></EMAIL>
    <WEBSITE>www.parausa.com</WEBSITE>
    <MAILSHOT>Y</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0169</CODE>
    <TYPE>P</TYPE>
    <COMPANY>OReilly + Lothrop</COMPANY>
    <STREET>100 Capitol Mall</STREET>
    <CITY>Sacramento</CITY>
    <STATE>CA</STATE>
    <ZIP>95811</ZIP>
    <CONTACT>Laura OReilly</CONTACT>
    <PHONE>9165231121</PHONE>
    <FAX>9165231000</FAX>
    <EMAIL>laura@patentsattorney.com</EMAIL>
    <WEBSITE>www.patentattorney.com</WEBSITE>
    <MAILSHOT>Y</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0179</CODE>
    <TYPE>O</TYPE>
    <COMPANY>Hoover Chimney Sweep</COMPANY>
    <STREET>11234 Equipment Road</STREET>
    <CITY>Worchester</CITY>
    <STATE>IA</STATE>
    <ZIP>66589</ZIP>
    <CONTACT>Jonathan Martin</CONTACT>
    <PHONE>2235568979</PHONE>
    <FAX>2235564111</FAX>
    <EMAIL></EMAIL>
    <WEBSITE></WEBSITE>
    <MAILSHOT>N</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0192</CODE>
    <TYPE>P</TYPE>
    <COMPANY>A1 Advertising</COMPANY>
    <STREET>25 Oahu Drive</STREET>
    <CITY>Waikiki</CITY>
    <STATE>HI</STATE>
    <ZIP>99558</ZIP>
    <CONTACT>Mickey Suarez</CONTACT>
    <PHONE>9056886868</PHONE>
    <FAX>9056886999</FAX>
    <EMAIL></EMAIL>
    <WEBSITE></WEBSITE>
    <MAILSHOT>N</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0198</CODE>
    <TYPE>C</TYPE>
    <COMPANY>Santucci Medical Supplies</COMPANY>
    <STREET>2001 Zinfandel Square</STREET>
    <CITY>Napa</CITY>
    <STATE>CA</STATE>
    <ZIP>95875</ZIP>
    <CONTACT>Michael Santucci</CONTACT>
    <PHONE>4187978888</PHONE>
    <FAX>4187978856</FAX>
    <EMAIL>info@santucci.com</EMAIL>
    <WEBSITE>www.santuccimedical.com</WEBSITE>
    <MAILSHOT>Y</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0199</CODE>
    <TYPE>S</TYPE>
    <COMPANY>Cellar Cafe</COMPANY>
    <STREET>1256 Nimbus Road</STREET>
    <CITY>Cameron Park</CITY>
    <STATE>CA</STATE>
    <ZIP>95682</ZIP>
    <CONTACT>Ronald McDonald</CONTACT>
    <PHONE>9168930503</PHONE>
    <FAX>9168930809</FAX>
    <EMAIL>ronald_cellar@yahoo.com</EMAIL>
    <WEBSITE></WEBSITE>
    <MAILSHOT>N</MAILSHOT>
    <MEMO></MEMO>
    <SPARE></SPARE>
  </ROLODEX>

  <ROLODEX>
    <CODE>0201</CODE>
    <TYPE>C</TYPE>
    <COMPANY>Canada Yukon Wines</COMPANY>
    <STREET>24567 Merlot Lane</STREET>
    <CITY>New York</CITY>
    <STATE>NY</STATE>
    <ZIP>00022</ZIP>
    <CONTACT>Robert Funk</CONTACT>
    <PHONE>4148792256</PHONE>
    <FAX></FAX>
    <EMAIL>robert@canadayukon.com</EMAIL>
    <WEBSITE>www.canadayukonwines.com</WEBSITE>
    <MAILSHOT>Y</MAILSHOT>
