=== SteveIves/Demos/Language/UTILITY/test/sdsgcm.dtd
<?xml version="1.0"?>

  <!ELEMENT SDSGCM_LIST (SDSGCM*)>

    <!ELEMENT SDSGCM (NONAME_001?,SGCSGC?,SGCKY0?,SGCSGD,NONAME_002?)>

      <!ELEMENT NONAME_001 (#PCDATA)>
      <!ELEMENT SGCSGC (#PCDATA)>
      <!ELEMENT SGCKY0 (#PCDATA)>
      <!ELEMENT SGCSGD (#PCDATA)>
      <!ELEMENT NONAME_002 (#PCDATA)>

=== SteveIves/Demos/Language/UTILITY/test/sdsgcm.xml
<?xml version="1.0"?>

<!DOCTYPE SDSGCM_LIST SYSTEM "sdsgcm.dtd">

<SDSGCM_LIST>

  <SDSGCM>
    <NONAME_001>A</NONAME_001>
    <SGCSGC>BRAKE</SGCSGC>
    <SGCKY0>BRAKE</SGCKY0>
    <SGCSGD>Brake Service</SGCSGD>
    <NONAME_002></NONAME_002>
  </SDSGCM>

  <SDSGCM>
    <NONAME_001>A</NONAME_001>
    <SGCSGC>GEN</SGCSGC>
    <SGCKY0>GEN</SGCKY0>
    <SGCSGD>General Services</SGCSGD>
    <NONAME_002></NONAME_002>
  </SDSGCM>

  <SDSGCM>
    <NONAME_001>A</NONAME_001>
    <SGCSGC>LABOR</SGCSGC>
    <SGCKY0>LABOR</SGCKY0>
    <SGCSGD>Service Labor</SGCSGD>
    <NONAME_002></NONAME_002>
  </SDSGCM>

  <SDSGCM>
    <NONAME_001>A</NONAME_001>
    <SGCSGC>MECH</SGCSGC>
    <SGCKY0>MECH</SGCKY0>
    <SGCSGD>Mechanical Services</SGCSGD>
    <NONAME_002></NONAME_002>
  </SDSGCM>

  <SDSGCM>
    <NONAME_001>A</NONAME_001>
    <SGCSGC>TIRE</SGCSGC>
    <SGCKY0>TIRE</SGCKY0>
    <SGCSGD>Tire Services</SGCSGD>
    <NONAME_002></NONAME_002>
  </SDSGCM>

  <SDSGCM>
    <NONAME_001>A</NONAME_001>
    <SGCSGC>TOW</SGCSGC>
    <SGCKY0>TOW</SGCKY0>
    <SGCSGD>Towing Services</SGCSGD>
    <NONAME_002></NONAME_002>
  </SDSGCM>

</SDSGCM_LIST>
